REPO_PATH="RocketChat/Rocket.Chat.Electron"
ASSET_NAME="rocketchat-VERSION-linux-x64.tar.gz"
BINARY_NAME="rocketchat-desktop"
APP_DIR="rocketchat"
DESCRIPTION="The Rocket.Chat email and team chat desktop client."