name: Update APT Repository

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Debian development utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-utils curl dpkg-dev gzip

      - name: Execute builder script
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          chmod +x build-repo.sh
          ./build-repo.sh

      - name: Setup GitHub Pages infrastructure
        uses: actions/configure-pages@v4
        
      - name: Upload static artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # We deploy the public folder generated by our build-repo.sh script
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
